# -*- coding: utf-8 -*-
"""Week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRaqjECeZJjyzanmbWPzk7z5fVfRgh4Z
"""

!pip install yt-dlp

"""#01 Week

Task-1: Our first task is to extract multiple images from a video using "ffmpeg". Download a youtube video of short duration, and extract multiple images from the video, using ffmpeg. (In a linux environment this is pretty simple.) Search Google on how to use "ffmpeg" for extracting multiple images from videos.
"""



!yt-dlp -f mp4 -o video.mp4 https://youtu.be/l-S7TBFCIiE?si=jIqHzE_p5ML5Z2ez

!ffmpeg -i video.mp4 -vf "fps=1" frame_%04d.png

from IPython.display import Image, display
import glob

images = sorted(glob.glob("frame_*.png"))[:5]

for img in images:
    display(Image(filename=img))

"""Task-2: In the first task you downloaded a video from YouTube (yt-dlp - utility in Linux) and chopped it into frames of images using ffmpeg. Now, you should repeat the process once again, generating some 30 frames per second on a 1 minute continuous portion of the video (30x60 = 1800 images) creating around 1800 images. These 1800 images are to be re-converted into a video of 1 minute duration at frame rate of 30 (ffmpeg can be used here too)."""

!ffmpeg -ss 00:00:00 -t 00:01:00 -i video.mp4 -vf "fps=30" frames_%04d.png

!ls frames_*.png | wc -l

!ffmpeg -framerate 30 -i frames_%04d.png -c:v libx264 -pix_fmt yuv420p output.mp4

!ls

from google.colab import files
files.download("output.mp4")

"""Task 03, please identify a song https://pixabay.com/music/search/1%20minute/ from any public portal, clip it to one minute duration using some utility like audacity, and merge audio track with your video (using ffmpeg) you just created from Task 02."""

from google.colab import files
uploaded = files.upload()



!ffmpeg -i output.mp4 -i audio.mp3 -c:v copy -c:a aac final_video.mp4

# !ls

files.download("final_video.mp4")

